apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: three-tier

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend

        image: 758024567313.dkr.ecr.ap-south-1.amazonaws.com/backend-repo:v2

        ports:
        - containerPort: 8085